server:
  port: 9090

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:mysql://localhost:3306/liu?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver